POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "root2",
    "name": "Superuser2",
    "password": "salainen2"
}