POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "eree",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "root",
    "password": "saewrwelainen"
}